name: Bug Report
description: File a bug report.
title: "[Bug]: "
projects: ["mind-of-my-own/5"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: broken-feature
    attributes:
      label: What feature is broken?
      description: Please provide a brief description of the feature that is broken.
      placeholder: "Feature name"
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a detailed list of steps to reproduce the bug.
      placeholder: "1. Go to '...' 2. Click on '...' 3. See error"
  - type: textarea
    id: expected-outcome
    attributes:
      label: "Expected outcome"
      placeholder: "What should happen?"
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Paste images while editing to upload and insert"
      placeholder: "Paste images here"
