name: Epic
description: "A ticket to trace a piece of work which is larger in scope than a discrete piece of work. We should be able to use it to track many other tickets, to achieve the epics goal."
projects: ["mind-of-my-own/5"]
type: Epic
body:
  - type: textarea
    id: epic-goal
    validations:
      required: true
    attributes:
      label: Epic Goal
      description: "What is the high level goal of this epic?"
      placeholder: "What is the high level goal of this epic?"