name: Spike
description: "Explore and gather information"
projects: ["mind-of-my-own/5"]
type: Spike
body:
  - type: markdown
    attributes:
      value: |
        What thing are you researching
  - type: input
    id: spike-problem-domain
    validations:
      required: true
    attributes:
      label: Spike problem
      description: "What is the problem domain you are researching?"
      placeholder: "What is the problem domain you are researching?"
  - type: textarea
    id: spike-outcome
    validations:
      required: true
    attributes:
      label: Spike Outcome
      description: "What is the outcome of the spike? What things do we need to know to call this spike complete?"
      placeholder: "What is the outcome of the spike? What things do we need to know to call this spike complete?"
