name: Spike
description: "Explore and gather information"
projects: ["mind-of-my-own/5"]
type: Spike
body:
  - type: markdown
    attributes:
      value: |
        What thing are you researching
  - type: textarea
    id: spike-problem-domain
    validations:
      required: true
    attributes:
      label: Spike problem
      description: "What is the problem domain you are researching?"
      placeholder: "What is the problem domain you are researching?"
  - type: input
    attributes:
      label: Timebox days
      description: How many days do you want to invest in solving the problem
    id: Timebox