name: Support Request
description: "Track larger features or initiatives"
projects: ["mind-of-my-own/5"]
type: Support
body:
  - type: markdown
    attributes:
      value: |
        Please provide information about the support request.
  - type: textarea
    id: support-request
    validations:
      required: true
    attributes:
      label: Support Request
      description: "What is the support request?"
      placeholder: "What is the support request?"
  - type: input
    id: existing-link
    attributes:
      label: Existing Work link
      description: "Do you have a link to a time when it's been done in the past?"
      placeholder: "Ticket link"
  - type: checkboxes
    attributes:
      label: Do we have the user's permission to access their account and view their data?
      options:
        - label: "Yes"
          required: false
