name: Theme
description: "Largest unit of work - can have many epics. Represents multi-sprint/feature piece of work"
projects: ["mind-of-my-own/5"]
type: Task
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out the high level goals of this work